import { Difficulty } from "../../../utility/difficultyColor";

const markdown = (...lines: string[]) =>
  ["## Explanation", "", ...lines].join("\n");

export const jsQuestions = [
  {
    id: "javascript-overview",
    title: "What is JavaScript, and what are its main features?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "JavaScript is a dynamic, high-level programming language used in browsers, servers, and other runtimes. It supports multiple styles, including functional and object-oriented programming.",
      "",
      "Core characteristics include:",
      "- **Dynamic typing:** values have types; variables can refer to values of different types over time.",
      "- **First-class functions:** functions can be stored, passed, and returned like other values.",
      "- **Prototype-based objects:** objects can inherit behavior from other objects.",
      "- **Event-driven APIs:** runtimes expose events, timers, and asynchronous operations.",
      "",
      "```js",
      "const greet = (name) => `Hello, ${name}`;",
      "console.log(greet('Ada'));",
      "```",
      "",
      "The ECMAScript specification defines the language. A runtime such as a browser or Node.js provides host APIs such as the DOM, timers, and file access.",
      "",
      "**Follow-up questions**",
      "- What is the difference between JavaScript and ECMAScript?",
      "- Which APIs come from the browser rather than the language itself?",
    ),
  },
  {
    id: "var-let-const",
    title: "What is the difference between `var`, `let`, and `const`?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "The main differences are scope, redeclaration, and reassignment:",
      "",
      "| Declaration | Scope | Redeclare in same scope? | Reassign? |",
      "| --- | --- | --- | --- |",
      "| `var` | Function | Yes | Yes |",
      "| `let` | Block | No | Yes |",
      "| `const` | Block | No | No |",
      "",
      "`let` and `const` are in a temporal dead zone from the start of their scope until their declaration is evaluated. A `const` binding cannot be reassigned, but an object or array stored in it can still be mutated.",
      "",
      "```js",
      "const user = { name: 'Ada' };",
      "user.name = 'Grace'; // allowed",
      "// user = {};        // TypeError: cannot reassign const",
      "```",
      "",
      "Prefer `const` by default, use `let` for reassigned bindings, and avoid `var` in modern code unless its function-scoping behavior is specifically needed.",
      "",
      "**Follow-up questions**",
      "- What is the temporal dead zone?",
      "- Does `const` make an object immutable?",
    ),
  },
  {
    id: "primitive-reference-types",
    title: "What is the difference between primitive and reference values?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "JavaScript primitives are `string`, `number`, `bigint`, `boolean`, `undefined`, `symbol`, and `null`. Objects, arrays, and functions are object values.",
      "",
      "| Behavior | Primitive | Object value |",
      "| --- | --- | --- |",
      "| Assignment | Copies the value | Copies the reference |",
      "| Equality | Compares the value | Usually compares identity |",
      "| Mutation | Values are immutable | Properties may be mutable |",
      "",
      "```js",
      "let first = 3;",
      "let second = first;",
      "second = 4; // first is still 3",
      "",
      "const original = { score: 3 };",
      "const copy = original;",
      "copy.score = 4; // original.score is now 4",
      "```",
      "",
      "The reference itself is copied; assigning an object does not automatically clone its properties. `null` is a primitive even though `typeof null` historically returns `\"object\"`.",
      "",
      "**Follow-up questions**",
      "- Why can two objects with identical properties compare unequal?",
      "- What does a shallow copy copy?",
    ),
  },
  {
    id: "strict-equality",
    title: "What is the difference between `==` and `===`?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "`===` compares without type coercion. `==` may convert operands to compatible types before comparing, which can produce surprising results.",
      "",
      "| Expression | Result | Reason |",
      "| --- | --- | --- |",
      "| `5 === '5'` | `false` | Different types |",
      "| `5 == '5'` | `true` | String is coerced to a number |",
      "| `null == undefined` | `true` | Special loose-equality rule |",
      "| `{} === {}` | `false` | Different object identities |",
      "",
      "Use `===` by default. Loose equality has a narrow useful case such as `value == null`, which checks for either `null` or `undefined`, but consistent strict comparisons are easier to reason about.",
      "",
      "**Follow-up questions**",
      "- Why are `NaN === NaN` and `Object.is(NaN, NaN)` different?",
      "- How does `Object.is` differ from strict equality for `-0`?",
    ),
  },
  {
    id: "hoisting-tdz",
    title: "What is hoisting, and how does the temporal dead zone work?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Hoisting describes how declarations are processed when JavaScript creates a scope. It does not mean source code is physically moved.",
      "",
      "- Function declarations can generally be called before their declaration in the same scope.",
      "- `var` declarations are initialized to `undefined` when the scope is created.",
      "- `let` and `const` bindings exist before their declaration runs but cannot be accessed in the temporal dead zone.",
      "",
      "```js",
      "console.log(value); // undefined",
      "var value = 1;",
      "",
      "// console.log(count); // ReferenceError",
      "let count = 1;",
      "```",
      "",
      "The declaration is scoped; the assignment remains at its original execution point. This is why reading a `var` too early gives `undefined`, while reading a `let` or `const` too early throws.",
      "",
      "**Follow-up questions**",
      "- How does a function expression differ from a function declaration during initialization?",
      "- Can a `let` variable be accessed before its declaration if it is in a different block?",
    ),
  },
  {
    id: "scope-lexical-environment",
    title: "What is lexical scope in JavaScript?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Lexical scope means a function's access to variables is determined by where the function is written, not where it is called. When a name is not found locally, JavaScript searches outward through enclosing scopes.",
      "",
      "```js",
      "const language = 'JavaScript';",
      "",
      "function createMessage() {",
      "  const greeting = 'Hello';",
      "  return function showMessage() {",
      "    return `${greeting}, ${language}`;",
      "  };",
      "}",
      "```",
      "",
      "The returned function can access bindings from its lexical environment. This relationship is the basis of closures. `let` and `const` also introduce block-scoped bindings; `var` is function-scoped.",
      "",
      "**Follow-up questions**",
      "- How does lexical scope lead to a closure?",
      "- What is the difference between block scope and function scope?",
    ),
  },
  {
    id: "closures",
    title: "What is a closure, and when is it useful?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A closure is a function together with access to the lexical bindings from the scope where it was created. The outer function can finish, yet the inner function can continue to use those bindings.",
      "",
      "```js",
      "function createCounter() {",
      "  let count = 0;",
      "  return () => ++count;",
      "}",
      "",
      "const next = createCounter();",
      "next(); // 1",
      "next(); // 2",
      "```",
      "",
      "Closures are used for callbacks, event handlers, factories, and private state. They can also retain large objects longer than expected if a long-lived callback still references them.",
      "",
      "**Follow-up questions**",
      "- How can closures keep data private?",
      "- How can a closure accidentally cause memory to remain reachable?",
    ),
  },
  {
    id: "this-arrow-functions",
    title: "How does `this` work, and how do arrow functions differ?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "For ordinary functions, `this` is determined by how the function is called. A method call such as `user.describe()` sets `this` to `user`; a detached function call does not preserve that receiver automatically.",
      "",
      "Arrow functions do not create their own `this`. They capture it lexically from the surrounding scope, so they are useful for callbacks but usually not as object methods that need a dynamic receiver.",
      "",
      "```js",
      "const user = {",
      "  name: 'Ada',",
      "  describe() {",
      "    return this.name;",
      "  },",
      "};",
      "```",
      "",
      "`call`, `apply`, and `bind` can provide a receiver to an ordinary function. They cannot replace the lexical `this` of an arrow function.",
      "",
      "**Follow-up questions**",
      "- What does `this` refer to in a detached method call?",
      "- Why are arrow functions often used in callbacks?",
    ),
  },
  {
    id: "prototypes",
    title: "What is the prototype chain, and how does inheritance work in JavaScript?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Objects can have another object as their prototype. When a property is not found directly on an object, JavaScript looks up the prototype chain until it finds the property or reaches `null`.",
      "",
      "```js",
      "const animal = { speak() { return 'sound'; } };",
      "const dog = Object.create(animal);",
      "dog.name = 'Milo';",
      "dog.speak(); // found on animal",
      "```",
      "",
      "The `class` syntax is built on JavaScript's prototype model and provides a clearer syntax for constructors and methods. Prefer `Object.create` or classes over directly mutating an object's prototype with `__proto__`.",
      "",
      "**Follow-up questions**",
      "- What is the difference between an own property and an inherited property?",
      "- How do `Object.create` and the `class` syntax relate to prototypes?",
    ),
  },
  {
    id: "event-loop",
    title: "How does the JavaScript event loop handle asynchronous work?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "JavaScript runs synchronous code on a call stack. The host runtime manages asynchronous operations, then queues their callbacks. The event loop schedules queued work when the stack is clear.",
      "",
      "Promise reactions and `queueMicrotask` callbacks use the microtask queue. Timers and many host events use task queues. After a task completes, the runtime drains microtasks before moving on to another task, though exact host scheduling details can vary.",
      "",
      "![JavaScript event loop](/javascript-event-loop.svg \"width=760\")",
      "",
      "```js",
      "console.log('sync');",
      "setTimeout(() => console.log('task'), 0);",
      "Promise.resolve().then(() => console.log('microtask'));",
      "// sync, microtask, task",
      "```",
      "",
      "A zero-delay timer means the callback is eligible to run later; it does not run immediately or preempt the current stack.",
      "",
      "**Follow-up questions**",
      "- Why does a resolved Promise usually run before a zero-delay timer?",
      "- What can happen if code continuously queues microtasks?",
    ),
  },
  {
    id: "promises-async-await",
    title: "How do Promises and `async`/`await` work?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A Promise represents the eventual result of an asynchronous operation. It is pending, fulfilled with a value, or rejected with a reason. `async` functions always return Promises; `await` pauses that function until the awaited Promise settles, without blocking the JavaScript thread.",
      "",
      "Promise combinators coordinate multiple operations:",
      "",
      "| Method | Fulfills when | Rejects when |",
      "| --- | --- | --- |",
      "| `Promise.all` | Every input fulfills | Any input rejects |",
      "| `Promise.allSettled` | Every input settles | It normally does not reject for input failures |",
      "| `Promise.race` | The first input settles | The first input rejects |",
      "| `Promise.any` | The first input fulfills | Every input rejects, with an `AggregateError` |",
      "",
      "```js",
      "async function loadUser(id) {",
      "  try {",
      "    const response = await fetch(`/api/users/${id}`);",
      "    if (!response.ok) throw new Error('Request failed');",
      "    return await response.json();",
      "  } catch (error) {",
      "    console.error('Could not load user', error);",
      "    throw error;",
      "  }",
      "}",
      "```",
      "",
      "Use `try/catch` around awaited operations when you need local error handling. A rejected Promise can also be handled with `.catch()`. Avoid starting independent work sequentially if it can safely run in parallel with `Promise.all`.",
      "",
      "**Follow-up questions**",
      "- What happens when an `async` function throws?",
      "- How would you run two independent requests concurrently?",
    ),
  },
  {
    id: "array-methods",
    title: "How do `map`, `filter`, and `reduce` differ?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "These array methods process items but communicate different intent:",
      "",
      "| Method | Purpose | Result |",
      "| --- | --- | --- |",
      "| `map` | Transform every item | New array of equal length |",
      "| `filter` | Keep items that pass a test | New array of zero or more items |",
      "| `reduce` | Accumulate items into a result | One accumulated value |",
      "",
      "```js",
      "const prices = [10, 20, 30];",
      "const withTax = prices.map((price) => price * 1.1);",
      "const affordable = prices.filter((price) => price < 25);",
      "const total = prices.reduce((sum, price) => sum + price, 0);",
      "```",
      "",
      "These methods do not mutate the original array by themselves, but a callback can still mutate an object stored in the array. Provide an initial accumulator to `reduce` when possible, especially for empty arrays.",
      "",
      "**Follow-up questions**",
      "- What does `reduce` return for an empty array with no initial value?",
      "- How can you chain `filter` and `map` without mutating the source?",
    ),
  },
  {
    id: "shallow-deep-copy",
    title: "What is the difference between a shallow copy and a deep copy?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A shallow copy creates a new outer object but keeps references to nested objects. A deep copy recursively duplicates nested data, subject to the copy method's supported value types.",
      "",
      "```js",
      "const original = { profile: { name: 'Ada' } };",
      "const shallow = { ...original };",
      "shallow.profile.name = 'Grace';",
      "console.log(original.profile.name); // Grace",
      "```",
      "",
      "`structuredClone(value)` handles many built-in data types and circular references, but it cannot clone every value, such as functions or DOM nodes. JSON serialization is more limited: it loses or changes values such as `undefined`, `BigInt`, `Date`, and circular references.",
      "",
      "**Follow-up questions**",
      "- Why does the spread operator make only a shallow copy?",
      "- Which values cannot be cloned with `structuredClone`?",
    ),
  },
  {
    id: "debounce-throttle",
    title: "What is the difference between debouncing and throttling?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Both techniques reduce how often a function runs during frequent events, but they choose different times to run it.",
      "",
      "| Technique | Runs when | Common use |",
      "| --- | --- | --- |",
      "| Debounce | After events stop for a delay | Search input, autosave |",
      "| Throttle | At most once per time interval | Scroll or pointer tracking |",
      "",
      "A debounced function resets its timer on each new event. A throttled function limits calls to a maximum rate. Both should provide a way to cancel pending work when a component or owner no longer needs it.",
      "",
      "**Follow-up questions**",
      "- Which technique is better for an autocomplete request, and why?",
      "- How should a debounced callback be cleaned up on unmount?",
    ),
  },
  {
    id: "es-modules",
    title: "How do JavaScript ES modules work?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "ES modules use `export` to expose bindings and `import` to consume them. A module has its own scope, and its imports and exports are statically analyzable by tools.",
      "",
      "```js",
      "// math.js",
      "export const add = (a, b) => a + b;",
      "export default function multiply(a, b) {",
      "  return a * b;",
      "}",
      "",
      "// app.js",
      "import multiply, { add } from './math.js';",
      "```",
      "",
      "Named exports are imported by name and can coexist. A module has at most one default export. Static imports are top-level; `import()` loads a module dynamically and returns a Promise.",
      "",
      "**Follow-up questions**",
      "- What is the difference between a named export and a default export?",
      "- When is dynamic `import()` useful?",
    ),
  },
  {
    id: "event-delegation",
    title: "What is event delegation, and why is it useful?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Event delegation attaches one listener to a common ancestor instead of attaching a separate listener to every child. It relies on event bubbling: an event from a descendant travels up through its ancestors.",
      "",
      "```js",
      "list.addEventListener('click', (event) => {",
      "  const button = event.target.closest('button[data-id]');",
      "  if (!button || !list.contains(button)) return;",
      "  selectItem(button.dataset.id);",
      "});",
      "```",
      "",
      "This can simplify handling large or dynamically changing lists. Check that the target is within the intended container, and account for events that do not bubble or have special propagation behavior.",
      "",
      "**Follow-up questions**",
      "- What is the difference between `event.target` and `event.currentTarget`?",
      "- How can `stopPropagation()` affect delegated handlers?",
    ),
  },
  {
    id: "event-loop-order",
    title: "How would you predict the order of microtasks and timer callbacks?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "First run the current synchronous stack. Then, when the stack is clear, drain the microtask queue before the next task. A microtask queued by another microtask is also handled during that drain.",
      "",
      "```js",
      "console.log('A');",
      "setTimeout(() => console.log('B'), 0);",
      "Promise.resolve().then(() => {",
      "  console.log('C');",
      "  queueMicrotask(() => console.log('D'));",
      "});",
      "console.log('E');",
      "```",
      "",
      "The output is `A`, `E`, `C`, `D`, `B`. The timer callback is a later task; the Promise reaction and `queueMicrotask` callback run as microtasks first.",
      "",
      "Long-running synchronous work blocks both queues. An endless chain of microtasks can also delay timers and rendering because the queue must be drained.",
      "",
      "**Follow-up questions**",
      "- What changes if a second Promise callback is queued inside the first one?",
      "- Why can a zero-delay timer still run much later than expected?",
    ),
  },
  {
    id: "promise-concurrency-limiter",
    title: "How would you limit the number of concurrent asynchronous tasks?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "A concurrency limiter starts no more than a fixed number of tasks at once. A worker repeatedly takes the next item and awaits its task; multiple workers share the same queue position.",
      "",
      "```js",
      "async function mapWithLimit(items, limit, task) {",
      "  const results = new Array(items.length);",
      "  let nextIndex = 0;",
      "",
      "  async function worker() {",
      "    while (nextIndex < items.length) {",
      "      const index = nextIndex++;",
      "      results[index] = await task(items[index], index);",
      "    }",
      "  }",
      "",
      "  await Promise.all(",
      "    Array.from({ length: Math.min(limit, items.length) }, worker),",
      "  );",
      "  return results;",
      "}",
      "```",
      "",
      "Validate that `limit` is a positive integer. This version rejects if a task rejects; production code may need an explicit policy for continuing, stopping, cancellation, and collecting individual errors.",
      "",
      "**Follow-up questions**",
      "- How would you preserve input order when tasks finish out of order?",
      "- How would you change the function to collect errors instead of rejecting early?",
    ),
  },
  {
    id: "garbage-collection-memory-leaks",
    title: "How does garbage collection work, and what causes memory leaks in JavaScript?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "JavaScript runtimes automatically reclaim memory that is no longer reachable from program roots, such as active stack values and global references. Modern engines commonly use tracing strategies related to mark-and-sweep, with optimizations for different object lifetimes.",
      "",
      "A memory leak occurs when data is no longer useful but remains reachable. Common causes include:",
      "- Unremoved event listeners or subscriptions.",
      "- Timers that continue running and retain closures.",
      "- Unbounded caches or collections.",
      "- Detached DOM nodes still referenced by JavaScript.",
      "",
      "```js",
      "const onResize = () => updateLayout();",
      "window.addEventListener('resize', onResize);",
      "// Later, when no longer needed:",
      "window.removeEventListener('resize', onResize);",
      "```",
      "",
      "Garbage collection does not understand whether an application still needs an object; it only considers reachability. Use browser memory tools to inspect retained objects and their retaining paths.",
      "",
      "**Follow-up questions**",
      "- Why can a closure retain memory?",
      "- When can `WeakMap` be useful for object-associated metadata?",
    ),
  },
  {
    id: "iterators-generators",
    title: "What are iterators and generators, and when are they useful?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "An iterator follows the iterator protocol: it has a `next()` method that returns `{ value, done }`. An iterable provides a `Symbol.iterator` method that returns an iterator; arrays, strings, Maps, and Sets are built-in iterables.",
      "",
      "A generator function, declared with `function*`, creates an iterator. Each `yield` pauses the generator and produces a value; calling `next()` resumes it.",
      "",
      "```js",
      "function* ids() {",
      "  yield 'a';",
      "  yield 'b';",
      "}",
      "",
      "for (const id of ids()) {",
      "  console.log(id);",
      "}",
      "```",
      "",
      "Generators can model lazy sequences or custom iteration without building a full array up front. Async generators combine this pattern with `for await...of` for asynchronous streams.",
      "",
      "**Follow-up questions**",
      "- What is the difference between an iterable and an iterator?",
      "- How does an async generator differ from a regular generator?",
    ),
  },
];