import { Difficulty } from "../../../utility/difficultyColor";

const markdown = (...lines: string[]) =>
  ["## Explanation", "", ...lines].join("\n");

export const reactTheoryQuestions = [
  {
    id: "what-is-react",
    title: "What is React, and what are its main features?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "React is a JavaScript library for building user interfaces. You describe what the UI should look like for the current data, and React updates the interface when that data changes.",
      "",
      "Key ideas:",
      "- **Component-based UI:** build screens from small, reusable components.",
      "- **Declarative rendering:** describe the desired UI instead of manually changing DOM nodes.",
      "- **One-way data flow:** pass data from parents to children with props.",
      "- **State and Hooks:** add component state and reusable behavior to function components.",
      "- **Efficient updates:** React reconciles new render output with the previous output before committing necessary DOM changes.",
      "",
      '![React logo](https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg "width=96 height=96")',
      "",
      "```jsx",
      "function Greeting({ name }) {",
      "  return <h1>Hello, {name}!</h1>;",
      "}",
      "```",
      "",
      "React handles the UI layer. Routing, server rendering, and data fetching are commonly provided by additional libraries or frameworks.",
      "",
      "**Follow-up questions**",
      "- How does React decide which DOM updates are necessary?",
      "- What responsibilities belong to a React framework rather than React itself?",
    ),
  },
  {
    id: "props-vs-state",
    title: "What is the difference between props and state in React?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "Both props and state are inputs to rendering, but they have different owners.",
      "",
      "- **Props** are passed into a component by its parent. The receiving component should treat them as read-only.",
      "- **State** is owned by a component and updated with a state setter or reducer dispatch.",
      "- A parent can pass its state to a child as props, connecting the two concepts.",
      "",
      "```jsx",
      "function Greeting({ name }) {",
      "  return <p>Hello, {name}!</p>;",
      "}",
      "",
      "function App() {",
      "  const [name, setName] = useState('Ada');",
      "  return <Greeting name={name} />;",
      "}",
      "```",
      "",
      "Keep state in the component that owns the change or coordinates the components that need it. Derive values from props and state when possible instead of storing duplicate data.",
      "",
      "**Follow-up questions**",
      "- When should state be lifted to a parent?",
      "- Why should a child avoid mutating an object received through props?",
    ),
  },
  {
    id: "virtual-dom",
    title: "What is the Virtual DOM, and how does React use it?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "The Virtual DOM is a common name for React's in-memory representation of the UI. A component render produces React elements describing the next UI; React compares that output with the previous one during reconciliation.",
      "",
      "At a high level:",
      "1. Props or state change.",
      "2. React renders the affected component tree to new elements.",
      "3. React reconciles the new output with the previous output.",
      "4. React commits the required changes to the host environment, such as the browser DOM.",
      "",
      '![React update flow](/react-update-flow.svg "width=720")',
      "",
      "The Virtual DOM is not a second browser DOM, and React does not necessarily diff every node in the whole application. Component identity, element type, and list keys help React determine what can be reused.",
      "",
      "**Follow-up questions**",
      "- What is reconciliation?",
      "- How do keys affect the identity of elements in a list?",
    ),
  },
  {
    id: "controlled-uncontrolled",
    title:
      "What is the difference between controlled and uncontrolled components?",
    difficulty: Difficulty.Easy,
    description: markdown(
      "This distinction usually refers to form inputs.",
      "",
      "- **Controlled input:** React state is the source of truth. Set `value` and update it in `onChange`.",
      "- **Uncontrolled input:** the DOM keeps the current value. Set an initial `defaultValue` and read it through a ref when needed.",
      "",
      "| Aspect | Controlled | Uncontrolled |",
      "| --- | --- | --- |",
      "| Source of truth | React state | DOM element |",
      "| Current value | Read from state | Read from a ref or form |",
      "| Updates | `onChange` updates state | Browser updates the input |",
      "| Best fit | Validation and reactive UI | Simple forms and integrations |",
      "",
      "```jsx",
      "function ControlledName() {",
      "  const [name, setName] = useState('');",
      "  return <input value={name} onChange={(event) => setName(event.target.value)} />;",
      "}",
      "",
      "function UncontrolledName() {",
      "  const inputRef = useRef(null);",
      "  return <input ref={inputRef} defaultValue='' />;",
      "}",
      "```",
      "",
      "Controlled inputs make validation and conditional UI straightforward. Uncontrolled inputs can be convenient for simple forms or when integrating with non-React code.",
      "",
      "**Follow-up questions**",
      "- Why should a controlled input update its value during `onChange`?",
      "- What is the difference between `value` and `defaultValue`?",
    ),
  },
  {
    id: "hooks-purpose",
    title: "What are React Hooks, and why were they introduced?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Hooks are functions such as `useState`, `useEffect`, and `useContext` that let function components use React features. They provide a way to reuse stateful logic without class components or patterns such as render props and higher-order components.",
      "",
      "```jsx",
      "function Counter() {",
      "  const [count, setCount] = useState(0);",
      "  return <button onClick={() => setCount((value) => value + 1)}>Count: {count}</button>;",
      "}",
      "```",
      "",
      "Call Hooks at the top level of a function component or custom Hook. Do not call them conditionally, inside loops, or from ordinary functions; React relies on a consistent call order between renders.",
      "",
      "**Follow-up questions**",
      "- What problem do custom Hooks solve?",
      "- Why can’t Hooks be called conditionally?",
    ),
  },
  {
    id: "functional-lifecycle",
    title: "Explain the lifecycle of a function component using Hooks.",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Function components do not have class lifecycle methods, but effects let them synchronize with external systems as props and state change.",
      "",
      "- **After a commit:** an effect runs when its dependencies changed.",
      "- **Before an effect re-runs:** React calls the cleanup returned by its previous run.",
      "- **On unmount:** React calls the last cleanup.",
      "",
      "```jsx",
      "useEffect(() => {",
      "  const connection = connect(roomId);",
      "  return () => connection.disconnect();",
      "}, [roomId]);",
      "```",
      "",
      "An empty dependency array means the effect has no reactive dependencies; it is not a general-purpose guarantee that code runs exactly once. Development Strict Mode may run an extra setup-and-cleanup cycle to expose unsafe effects.",
      "",
      "**Follow-up questions**",
      "- In what order do effect setup and cleanup run when a dependency changes?",
      "- How does Strict Mode help find lifecycle bugs?",
    ),
  },
  {
    id: "use-effect-dependencies",
    title:
      "How does `useEffect` work, and how does its dependency array affect execution?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "`useEffect` synchronizes a component with an external system, such as a subscription, timer, or network connection. React runs the setup after a commit when one or more dependencies differ from the previous render using `Object.is`.",
      "",
      "```jsx",
      "useEffect(() => {",
      "  const connection = createConnection(serverUrl, roomId);",
      "  connection.connect();",
      "  return () => connection.disconnect();",
      "}, [serverUrl, roomId]);",
      "```",
      "",
      "- No dependency array: setup runs after every commit.",
      "- Empty array: no reactive dependencies; setup runs after the initial commit and cleanup on unmount.",
      "- Dependencies listed: setup runs after the initial commit and when a dependency changes.",
      "",
      "Include every reactive value read by the effect. If you only need to calculate data from props or state, calculate it during render instead of using an effect.",
      "",
      "**Follow-up questions**",
      "- Why can omitting a dependency create stale data?",
      "- When should `useLayoutEffect` be considered instead?",
    ),
  },
  {
    id: "use-state-vs-ref",
    title:
      "What is the difference between `useState` and `useRef`, and when would you use each?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Both Hooks preserve a value between renders, but only state participates in rendering.",
      "",
      "- Use **`useState`** when changing the value should update the UI. Its setter schedules a render.",
      "- Use **`useRef`** for a mutable value that does not itself need to update the UI, or to hold a DOM node.",
      "",
      "```jsx",
      "const [count, setCount] = useState(0); // visible state",
      "const timerId = useRef(null);          // timer handle",
      "```",
      "",
      "Changing `ref.current` does not trigger a render. Avoid using a ref as hidden state when the UI should respond to its changes.",
      "",
      "**Follow-up questions**",
      "- Why does updating `ref.current` not render again?",
      "- How can a ref be used to focus an input?",
    ),
  },
  {
    id: "rerender-causes",
    title: "What causes a React component to re-render?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A component commonly renders again when:",
      "- Its state is updated.",
      "- Its parent renders and React renders its children by default.",
      "- A context value it reads changes.",
      "- An external-store subscription reports a changed snapshot.",
      "",
      "A render calculates the next UI; it does not guarantee that the DOM changes. React may reuse the previous DOM when the output is equivalent. `memo` can skip some parent-driven renders when props compare equal, but it does not block updates from the component's own state or consumed context.",
      "",
      "```jsx",
      "const [query, setQuery] = useState('');",
      "return <input value={query} onChange={(event) => setQuery(event.target.value)} />;",
      "```",
      "",
      "**Follow-up questions**",
      "- Does every render cause a DOM update? Why not?",
      "- Which updates can `React.memo` skip, and which can it not skip?",
    ),
  },
  {
    id: "reconciliation",
    title: "How does React's reconciliation process work?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Reconciliation is React's process for comparing the output of a new render with the previous render and deciding what work is needed. React uses element types, positions, and keys to determine which component instances can be preserved and which must be replaced.",
      "",
      "For example, stable keys let React match list items after insertion or reordering. Changing a component's type or key tells React that it represents a different identity, which can reset its state.",
      "",
      "```jsx",
      "items.map((item) => <Row key={item.id} item={item} />);",
      "```",
      "",
      "Reconciliation determines a render result; the commit phase applies the necessary host changes. It is better to describe this as React comparing element trees than as React blindly diffing and rewriting the entire DOM.",
      "",
      "**Follow-up questions**",
      "- What happens to component state when its key changes?",
      "- How do element types affect whether React preserves a component?",
    ),
  },
  {
    id: "keys-indexes",
    title:
      "Why are keys important in lists, and what problems can array indexes cause?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Keys give sibling elements stable identities so React can match items between renders.",
      "",
      "```jsx",
      "users.map((user) => <UserRow key={user.id} user={user} />);",
      "```",
      "",
      "An array index is only a safe key when the list is static and items are never inserted, removed, or reordered. Otherwise, React may associate existing component state or DOM with the wrong item after positions shift. Random keys are also harmful because they make every item look new on each render.",
      "",
      "Keys need to be unique among siblings, not globally. They are used by React and are not passed to the component as a prop; pass an ID separately if the component needs it.",
      "",
      "**Follow-up questions**",
      "- Why can an index key break an editable list?",
      "- How can you preserve state when an item moves to a different position?",
    ),
  },
  {
    id: "prop-drilling",
    title: "What is prop drilling, and how can it be avoided?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "Prop drilling is passing data through components that do not use it only so a deeper descendant can receive it. It is not inherently bad; explicit props often make small component trees easier to understand.",
      "",
      "Choose an approach based on the relationship:",
      "- **Keep props:** the tree is small and the data flow is clear.",
      "- **Component composition:** pass a prepared child through a slot such as `children` when intermediates need not know the data.",
      "- **Context:** many descendants need the same value across a subtree.",
      "- **External store:** state is shared broadly or needs specialized update behavior.",
      "",
      "Avoid adding Context solely to eliminate every prop. Context adds an implicit dependency and should represent a value that is genuinely shared.",
      "",
      "**Follow-up questions**",
      "- How can component composition reduce prop drilling?",
      "- What trade-offs does Context introduce?",
    ),
  },
  {
    id: "context-api",
    title: "How does Context work, and when should or shouldn't you use it?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A Context object identifies a value. A provider supplies that value to descendants, and `useContext` reads the nearest matching provider.",
      "",
      "```jsx",
      "const ThemeContext = createContext('light');",
      "",
      "function Toolbar() {",
      "  const theme = useContext(ThemeContext);",
      "  return <button className={theme}>Save</button>;",
      "}",
      "```",
      "",
      "A consumer updates when its nearest provider's value changes according to `Object.is`. Context is useful for values shared across a subtree, such as theme or locale. Avoid it for local state used by one component or for rapidly changing data consumed by many unrelated parts of a large tree without considering update costs.",
      "",
      "**Follow-up questions**",
      "- What happens when a provider value is a new object on every render?",
      "- How might splitting Contexts reduce unnecessary consumer updates?",
    ),
  },
  {
    id: "memo-apis",
    title:
      "What is the difference between `React.memo`, `useMemo`, and `useCallback`?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "These APIs memoize different things:",
      "",
      "- **`React.memo(Component)`** can skip a parent-driven render when the component's props compare equal.",
      "- **`useMemo(calculate, dependencies)`** caches a calculated value between renders.",
      "- **`useCallback(function, dependencies)`** caches a function reference; it is conceptually similar to `useMemo(() => function, dependencies)`.",
      "",
      "```jsx",
      "const filteredItems = useMemo(() => filterItems(items, query), [items, query]);",
      "const handleSelect = useCallback((id) => onSelect(id), [onSelect]);",
      "```",
      "",
      "Memoization is a performance optimization, not a correctness tool. Add it when measurement or a clear rendering boundary shows a benefit, and keep dependencies complete.",
      "",
      "**Follow-up questions**",
      "- Why can a new object prop defeat `React.memo`?",
      "- When can memoization make code slower or harder to maintain?",
    ),
  },
  {
    id: "custom-hooks",
    title: "What are custom Hooks, and when should you create one?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "A custom Hook is a function whose name starts with `use` and that calls other Hooks. It extracts reusable stateful behavior from components without sharing component state automatically.",
      "",
      "```jsx",
      "function useWindowWidth() {",
      "  const [width, setWidth] = useState(window.innerWidth);",
      "  useEffect(() => {",
      "    const updateWidth = () => setWidth(window.innerWidth);",
      "    window.addEventListener('resize', updateWidth);",
      "    return () => window.removeEventListener('resize', updateWidth);",
      "  }, []);",
      "  return width;",
      "}",
      "```",
      "",
      "Create a custom Hook when multiple components need the same stateful behavior or synchronization logic. Each call has independent Hook state; use Context or an external store if the data itself must be shared.",
      "",
      "**Follow-up questions**",
      "- Why must a custom Hook follow the Rules of Hooks?",
      "- How would you test a custom Hook that subscribes to an event?",
    ),
  },
  {
    id: "state-batching",
    title:
      "How does state batching work, and why can multiple updates produce one render?",
    difficulty: Difficulty.Medium,
    description: markdown(
      "React can group multiple state updates from the same interaction and render after processing them, reducing redundant work. Batching affects when React renders; it does not make state setters mutate the current render's snapshot.",
      "",
      "When updates depend on previous state, use updater functions so React can apply them in sequence:",
      "",
      "```jsx",
      "setCount((count) => count + 1);",
      "setCount((count) => count + 1);",
      "setCount((count) => count + 1);",
      "```",
      "",
      "This increments by three. Three calls to `setCount(count + 1)` use the same captured `count` value and may produce only one increment. React 18 and later also batch updates from more asynchronous contexts when using a modern root.",
      "",
      "**Follow-up questions**",
      "- What does a state setter return?",
      "- When is `flushSync` useful, and why should it be rare?",
    ),
  },
  {
    id: "rendering-process",
    title:
      "How does React render and commit an update after props or state change?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "A state update or new props schedule React work. A simplified update proceeds as follows:",
      "",
      "1. **Schedule:** React records the update and assigns it an appropriate priority.",
      "2. **Render:** React calls affected components to calculate the next element tree.",
      "3. **Reconcile:** React compares the new output with the previous output and determines what should be preserved, added, removed, or changed.",
      "4. **Commit:** React applies the required host changes, updates refs, and runs layout effects. Passive effects run after the commit, generally after the browser paints.",
      "",
      "Concurrent rendering may pause, restart, or abandon render work before it commits. The commit phase is applied consistently; component render logic must therefore be pure and safe to repeat.",
      "",
      "**Follow-up questions**",
      "- Which work can React interrupt, and which work must be committed together?",
      "- When do `useLayoutEffect` and `useEffect` run relative to the commit?",
    ),
  },
  {
    id: "stale-closures",
    title: "What are stale closures in Hooks, and why do they occur?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "A closure captures the variables from the render in which a function was created. If a callback continues running after later renders, it can read values from an older render. This is called a stale closure.",
      "",
      "A timer with an empty dependency array captures the initial `count`:",
      "",
      "```jsx",
      "useEffect(() => {",
      "  const id = setInterval(() => setCount(count + 1), 1000);",
      "  return () => clearInterval(id);",
      "}, []); // count is from the initial render",
      "```",
      "",
      "If the callback only needs the previous state, use a functional update: `setCount((count) => count + 1)`. If it needs current props or state, include those values in the dependencies or restructure the synchronization. Do not suppress dependency warnings to hide stale values.",
      "",
      "**Follow-up questions**",
      "- How does a functional state update avoid capturing the old state?",
      "- When can `useEffectEvent` help separate event logic from effect synchronization?",
    ),
  },
  {
    id: "render-vs-commit",
    title:
      "What is the difference between React's render phase and commit phase?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "- **Render phase:** calls components and calculates the next UI. Work can be repeated, restarted, or abandoned, so keep it pure.",
      "- **Commit phase:** applies host changes, updates refs, and runs layout effects. React commits a consistent render result to the UI.",
      "",
      "This distinction matters because component functions are not one-time DOM commands. They describe a possible next UI. Side effects during render can run more than once or run for work that is never committed.",
      "",
      "Use `useLayoutEffect` for a layout read or write that must happen after DOM mutations and before paint. Use `useEffect` for most external synchronization that does not need to block paint.",
      "",
      "**Follow-up questions**",
      "- Why should rendering be idempotent and free of side effects?",
      "- What visual problem can `useLayoutEffect` prevent, and what is its cost?",
    ),
  },
  {
    id: "react-fiber",
    title:
      "What is React Fiber, and how does it help with rendering and update priority?",
    difficulty: Difficulty.Hard,
    description: markdown(
      "Fiber is React's internal architecture for representing component work as units that can be processed over time. It lets React track work, prioritize updates, and coordinate rendering instead of treating an entire tree update as one indivisible operation.",
      "",
      "This architecture supports capabilities such as interruptible render work and prioritizing urgent interactions over less urgent updates. React may pause or restart render work before commit, while keeping the committed UI consistent.",
      "",
      "Fiber is an implementation detail, not an API developers manipulate directly. It does not mean React renders on another JavaScript thread. Use public APIs such as `useTransition` to mark non-urgent updates.",
      "",
      "**Follow-up questions**",
      "- How do transitions communicate that an update is non-urgent?",
      "- Why must render functions remain pure when React can restart work?",
    ),
  },
];
